#!/bin/bash
#/home/dwade/.arduino15/packages/m5stack/tools/esptool_py/5.0.dev1/esptool --chip esp32s3 merge-bin -o /home/dwade/.cache/arduino/sketches/510BD06A3ADA27DC99D431792C8BDCCA/sketch_sep24a.ino.merged.bin --pad-to-size 16MB --flash-mode keep --flash-freq keep --flash-size keep 0x0 /home/dwade/.cache/arduino/sketches/510BD06A3ADA27DC99D431792C8BDCCA/sketch_sep24a.ino.bootloader.bin 0x8000 /home/dwade/.cache/arduino/sketches/510BD06A3ADA27DC99D431792C8BDCCA/sketch_sep24a.ino.partitions.bin 0xe000 /home/dwade/.arduino15/packages/m5stack/hardware/esp32/3.2.2/tools/partitions/boot_app0.bin 0x10000 /home/dwade/.cache/arduino/sketches/510BD06A3ADA27DC99D431792C8BDCCA/sketch_sep24a.ino.bin

/home/dwade/.arduino15/packages/m5stack/tools/esptool_py/5.0.dev1/esptool --chip esp32s3 --port /dev/ttyACM0 --baud 921600 flash_id

#  Connected to ESP32-S3 on /dev/ttyACM0:
#  Chip type:          ESP32-S3 (QFN56) (revision v0.2)
#  Features:           Wi-Fi, BT 5 (LE), Dual Core + LP Core, 240MHz
#  Crystal frequency:  40MHz
#  USB mode:           USB-Serial/JTAG
#  MAC:                30:ed:a0:d4:cb:8c
#  
#  Stub flasher running.
#  Changing baud rate to 921600...
#  Changed.
#  
#  Flash Memory Information:
#  =========================
#  Manufacturer: 46
#  Device: 4018
#  Detected flash size: 16MB
#  Flash type set in eFuse: quad (4 data lines)
#  Flash voltage set by a strapping pin: 3.3V
#  
#  Hard resetting via RTS pin...
#  

ask 'save'
if [ $? != 0 ]; then
    /home/dwade/.arduino15/packages/m5stack/tools/esptool_py/5.0.dev1/esptool --chip esp32s3 --port /dev/ttyACM0 --baud 921600 read_flash 0 0x1000000 espCore3s3.bin
fi

ask 'restore'
if [ $? != 0 ]; then
    /home/dwade/.arduino15/packages/m5stack/tools/esptool_py/5.0.dev1/esptool --chip esp32s3 --port /dev/ttyACM0 --baud 921600 --before default-reset --after hard-reset write-flash --flash-mode dio --flash-freq 80m --flash-size 16MB  0  espCore3s3.bin
fi

